# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 08:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminPortal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcompany',
            old_name='website',
            new_name='city',
        ),
    ]
